<html><head>
        <META http-equiv="content-type" content="text/html; charset=utf-8">
        <title>luad.error</title>
        </head><body>
        <h1>luad.error</h1>
        <!-- Generated by Ddoc from luad\error.d -->
<br><br>

<script>explorer.outline.incSymbolLevel();</script>
<dl>
<script>explorer.outline.writeEnabled = true;</script>
<dt><span class="decl">class 
<span class="currsymbol">LuaError</span>
<script>explorer.outline.addDecl('LuaError');</script>

: object.Exception;
</span></dt>
<script>explorer.outline.writeEnabled = false;</script>


<dd>Thrown on Lua panic.
<br><br>
This exception is only thrown if there is no protected Lua call (e.g. pcall)
 to handle the error. Whenever this documentation says a function throws
 a 
<span class="currsymbol">LuaError</span>
<script>explorer.outline.addDecl('LuaError');</script>

, no D exception is actually thrown if a Lua error handler is in place.
<br><br>

 Additionally, exceptions thrown in D functions given to Lua are converted to
 and propagated as Lua errors. You can subvert this by throwing an object not
 deriving from Exception (i.e. derive from Error, Throwable, etc).<br><br>

</dd>
</dl>
<script>explorer.outline.decSymbolLevel();</script>



        <hr><small>Page generated by <a href="http://www.digitalmars.com/d/2.0/ddoc.html">Ddoc</a>. </small>
        </body></html>
